# Generated by Django 4.2.20 on 2026-07-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_buyeraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='vertical_type',
            field=models.CharField(choices=[('automotive', 'Automotive'), ('architectural', 'Architectural'), ('construction', 'Construction'), ('dental', 'Dental'), ('dry_cleaning', 'Dry Cleaning'), ('education', 'Education'), ('electronics', 'Electronics'), ('food_beverage', 'Food & Beverage'), ('healthcare', 'Healthcare'), ('hospitality', 'Hospitality'), ('law_office', 'Law Office'), ('logistics', 'Logistics & Shipping'), ('manufacturing', 'Manufacturing'), ('real_estate', 'Real Estate'), ('retail', 'Retail'), ('technology', 'Technology'), ('textiles', 'Textiles & Apparel'), ('wholesale', 'Wholesale'), ('other', 'Other')], max_length=32),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='vertical_type',
            field=models.CharField(choices=[('automotive', 'Automotive'), ('architectural', 'Architectural'), ('construction', 'Construction'), ('dental', 'Dental'), ('dry_cleaning', 'Dry Cleaning'), ('education', 'Education'), ('electronics', 'Electronics'), ('food_beverage', 'Food & Beverage'), ('healthcare', 'Healthcare'), ('hospitality', 'Hospitality'), ('law_office', 'Law Office'), ('logistics', 'Logistics & Shipping'), ('manufacturing', 'Manufacturing'), ('real_estate', 'Real Estate'), ('retail', 'Retail'), ('technology', 'Technology'), ('textiles', 'Textiles & Apparel'), ('wholesale', 'Wholesale'), ('other', 'Other')], max_length=32),
        ),
    ]
