# Generated by Django 4.2.20 on 2026-07-08 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='webhookdelivery',
            new_name='webhooks_de_status_546645_idx',
            old_name='webhook_status_retry_idx',
        ),
    ]
