[pytest]
DJANGO_SETTINGS_MODULE = nepa_unite.settings.development
python_files = tests.py test_*.py *_tests.py
addopts = -ra --strict-markers --cov=. --cov-report=term-missing --cov-fail-under=80
testpaths = users products orders payments notifications webhooks contracts core tests
filterwarnings =
    ignore::DeprecationWarning
