# Generated by Django 4.2.20 on 2026-07-08 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_job'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_entity__244637_idx',
            old_name='core_auditlog_entity_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_actor_i_41600a_idx',
            old_name='core_auditlog_actor_idx',
        ),
    ]
