# Generated by Django 4.2.20 on 2026-06-12 07:06

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_cart_and_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=128, unique=True)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'commissions_commissionrate',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, default='', max_length=128)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('earned', 'Earned'), ('reversed', 'Reversed')], default='pending', max_length=16)),
                ('earned_at', models.DateTimeField(blank=True, null=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='orders.order')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commission', to='orders.orderitem')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'commissions_commission',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['seller', 'status'], name='commissions_seller__afe705_idx'), models.Index(fields=['status', 'created_at'], name='commissions_status_f59448_idx')],
            },
        ),
    ]
