# Generated by Django 4.2.20 on 2026-07-07 09:48

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_alter_tenant_vertical_type_and_more'),
        ('products', '0006_product_is_exchangeable_product_is_returnable_and_more'),
        ('orders', '0004_cart_and_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('return', 'Return'), ('exchange', 'Exchange')], default='return', max_length=16)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('pickup_scheduled', 'Pickup scheduled'), ('picked_up', 'Picked up'), ('received', 'Received'), ('refunded', 'Refunded'), ('exchange_shipped', 'Exchange shipped'), ('exchange_completed', 'Exchange completed')], default='requested', max_length=24)),
                ('reason', models.CharField(choices=[('defective', 'Defective / damaged'), ('wrong_item', 'Wrong item delivered'), ('not_as_described', 'Not as described'), ('size_fit', 'Size / fit issue'), ('no_longer_needed', 'No longer needed'), ('other', 'Other')], max_length=24)),
                ('reason_note', models.TextField(blank=True, default='')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('pickup_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('stripe_refund_id', models.CharField(blank=True, default='', max_length=255)),
                ('status_changed_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to=settings.AUTH_USER_MODEL)),
                ('exchange_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_requests', to='products.product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='orders.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='orders.orderitem')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller_returns', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='users.tenant')),
            ],
            options={
                'db_table': 'orders_returnrequest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, default='', max_length=24)),
                ('to_status', models.CharField(max_length=24)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_actions', to=settings.AUTH_USER_MODEL)),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.returnrequest')),
            ],
            options={
                'db_table': 'orders_returnevent',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['seller', 'status'], name='orders_retu_seller__e1ef71_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['buyer', 'status'], name='orders_retu_buyer_i_a8057a_idx'),
        ),
    ]
