# Generated by Django 4.2.20 on 2026-07-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_f39341_idx',
            old_name='notif_recipient_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('order_status', 'Order status'), ('payment', 'Payment'), ('account', 'Account'), ('system', 'System'), ('return', 'Return')], max_length=32),
        ),
    ]
