# Generated by Django 4.2.20 on 2026-07-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_mrp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_exchangeable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_returnable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='return_policy_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='return_window_days',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
